name: module_progress_dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - dash

# to create environment, type the following on terminal
# conda env create -f environment.yaml